server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/souvenir_shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Hibernate не трогает БД, всё через schema.sql
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

app:
  jwt:
    secret: "rScB4Z3KGOxU7ocOMVV/0cK/DXqyy9bgweZSyGswk+w="  # потом вынеси в .env
    expiration: 86400000
